### PR TITLE
Change tested ruby versions

### PR DESCRIPTION
**Pull request by cbaines**
Most apps use either 2.4 or 2.5, so lets test with those.

### CODE REVIEW

**Comment by tijmenb** [comment]
Can we use `buildProject()` instead? I think it'll test against our current Rubies in that script.

**Comment by cbaines** [comment]
> Can we use buildProject() instead? I think it'll test against our current Rubies in that script.

That sounds like a good idea, although it looks like the existing process is failing for some reason...

**Comment by cbaines** [comment]
> Can we use buildProject() instead? I think it'll test against our current Rubies in that script.

I've got that working here [1] now, but it doesn't yet remove the definition for `rubyVersions` as the test bit has to be overridden to keep testing against both Gemfiles.

1: https://github.com/alphagov/gds-sso/pull/140

**Comment by cbaines** [comment]
I'll leave improving `govuk-jenkinslib` to allow doing something around testing with multiple Gemfiles as a future improvement, and merge this now.

**Pull request merged**
